-- all PASS
INSERT INTO EMPLOYEE (EMPLOYEE_ID,PASSWORD,ROLE,LAST_MODIFIED_DATE, CREATED_DATE) VALUES (10012345, '$2a$10$FZ7P7IOFQuayu1Oo6BWRHeIAK4r/Bg85Sfy0evThp.IGj5J1KH.iG', 'MANAGER', CURRENT_DATE, CURRENT_DATE);
INSERT INTO EMPLOYEE (EMPLOYEE_ID,PASSWORD,ROLE,LAST_MODIFIED_DATE, CREATED_DATE) VALUES (10012346, '$2a$10$FZ7P7IOFQuayu1Oo6BWRHeIAK4r/Bg85Sfy0evThp.IGj5J1KH.iG', 'RECEPT', CURRENT_DATE, CURRENT_DATE);
INSERT INTO EMPLOYEE (EMPLOYEE_ID,PASSWORD,ROLE,LAST_MODIFIED_DATE, CREATED_DATE) VALUES (10012347, '$2a$10$FZ7P7IOFQuayu1Oo6BWRHeIAK4r/Bg85Sfy0evThp.IGj5J1KH.iG', 'HOUSEKE', CURRENT_DATE, CURRENT_DATE);

INSERT INTO HOTEL_DETAILS(ID,DAYS_OF_OPERATION,HOURS_OF_OPERATION,SINGLE_ROOM_PRICE,DOUBLE_ROOM_PRICE,SUITE_ROOM_PRICE) VALUES (1,'SUN-SAT','7AM-11PM',40.00,60.00,90.00);
